version: "3.9"

services:
  db_postgres:
    image: postgres
    container_name: fastapi_postgres_db
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build:
      context: .
    restart: always
    container_name: fastapi_web
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - type: bind
        source: .
        target: /code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres