"""Add cascade on survey ans question delete

Revision ID: 001ae79e1376
Revises: 1dd21dcccb77
Create Date: 2022-03-30 09:01:44.013115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001ae79e1376'
down_revision = '1dd21dcccb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_answer_question', 'answer', type_='foreignkey')
    op.create_foreign_key('fk_answer_question', 'answer', 'question', ['question_id'], ['question_id'], ondelete='CASCADE')
    op.drop_constraint('fk_question_survey', 'question', type_='foreignkey')
    op.create_foreign_key('fk_question_survey', 'question', 'survey', ['survey_id'], ['survey_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_question_survey', 'question', type_='foreignkey')
    op.create_foreign_key('fk_question_survey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.drop_constraint('fk_answer_question', 'answer', type_='foreignkey')
    op.create_foreign_key('fk_answer_question', 'answer', 'question', ['question_id'], ['question_id'])
    # ### end Alembic commands ###
