"""init basic tables

Revision ID: 1dd21dcccb77
Revises: 
Create Date: 2022-03-30 08:34:34.514371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd21dcccb77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_index(op.f('ix_survey_survey_id'), 'survey', ['survey_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.survey_id'], name='fk_question_survey'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    op.create_table('answer',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='fk_answer_question'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_answer_answer_id'), 'answer', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_answer_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_survey_survey_id'), table_name='survey')
    op.drop_table('survey')
    # ### end Alembic commands ###
